import { Inter } from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "5G 传感器状态",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className={inter.className}>
              <AntdRegistry>
                  {children}
              </AntdRegistry>
          </body>
      </html>
  );
}
